/*
 * All PolySync C api headers located in /usr/local/polysync/include
 *
 * Exceptions are the xsens, phidget and pointgrey headers which require 3rd party apis
 * so support isn't a default.
 *
 * To enable Cython support uncomment then run `python pxd_support.py` in this
 * project's `ps_util` directory. Then you use the `generated.pxd` to overwrite
 * the `polysync/__init__.pxd` to incorporate changes in the next build.
 */

//#include "/usr/local/polysync/include/pointgrey_gige_driver.h"
//#include "/usr/local/polysync/include/phidget_spatial_driver.h"
//#include "/usr/local/polysync/include/xsens_mt_driver.h"


#include "/usr/local/polysync/pdm/psyncDcps.h"
#include "/usr/local/polysync/include/deps/dcps/C/SAC/dds_dcps.h"
#include "/usr/local/polysync/include/deps/dcps/C/SAC/dds_builtinTopicsSacDcps.h"
#include "/usr/local/polysync/include/deps/dcps/C/SAC/dds_dcps_private.h"
#include "/usr/local/polysync/include/deps/dcps/C/SAC/dds_primitive_types.h"
#include "/usr/local/polysync/include/autoliv_mmr_77ghz_driver.h"
#include "/usr/local/polysync/include/autoliv_srr_c6_driver.h"
#include "/usr/local/polysync/include/continental_ars_driver.h"
#include "/usr/local/polysync/include/dataspeed_mkz_driver.h"
#include "/usr/local/polysync/include/delphi_esr_2_5_driver.h"
#include "/usr/local/polysync/include/delphi_esr_9_21_21_driver.h"
#include "/usr/local/polysync/include/delphi_rsds_left_driver.h"
#include "/usr/local/polysync/include/delphi_rsds_right_driver.h"
#include "/usr/local/polysync/include/delphi_srr_left_driver.h"
#include "/usr/local/polysync/include/delphi_srr_right_driver.h"
#include "/usr/local/polysync/include/ibeo_fusion_ecu_driver.h"
#include "/usr/local/polysync/include/ibeo_lux_4l_driver.h"
#include "/usr/local/polysync/include/ibeo_lux_hd_driver.h"
#include "/usr/local/polysync/include/ibeo_scala_driver.h"
#include "/usr/local/polysync/include/leddar_m16_driver.h"
#include "/usr/local/polysync/include/mobileye_560_driver.h"
#include "/usr/local/polysync/include/model_s_can_reader_driver.h"
#include "/usr/local/polysync/include/neobotix_usboard_driver.h"
#include "/usr/local/polysync/include/novatel_oem6_driver.h"
#include "/usr/local/polysync/include/obd_generic_driver.h"
#include "/usr/local/polysync/include/oxts_ncom.h"
#include "/usr/local/polysync/include/oxts_rt_driver.h"
#include "/usr/local/polysync/include/panasonic_us24_driver.h"
#include "/usr/local/polysync/include/polysync_can.h"
#include "/usr/local/polysync/include/polysync_core.h"
#include "/usr/local/polysync/include/polysync_dynamic_driver_commands.h"
#include "/usr/local/polysync/include/polysync_dynamic_driver.h"
#include "/usr/local/polysync/include/polysync_dynamic_driver_parameters.h"
#include "/usr/local/polysync/include/polysync_dynamic_interface.h"
#include "/usr/local/polysync/include/polysync_file_sync.h"
#include "/usr/local/polysync/include/polysync_file_transfer.h"
#include "/usr/local/polysync/include/polysync_getset.h"
#include "/usr/local/polysync/include/polysync_host.h"
#include "/usr/local/polysync/include/polysync_interface_util.h"
#include "/usr/local/polysync/include/polysync_logfile.h"
#include "/usr/local/polysync/include/polysync_message.h"
#include "/usr/local/polysync/include/polysync_node.h"
#include "/usr/local/polysync/include/polysync_node_ref.h"
#include "/usr/local/polysync/include/polysync_node_template.h"
#include "/usr/local/polysync/include/polysync_parameter_group.h"
#include "/usr/local/polysync/include/polysync_rnr.h"
#include "/usr/local/polysync/include/polysync_rnr_support.h"
#include "/usr/local/polysync/include/polysync_sdf.h"
#include "/usr/local/polysync/include/polysync_serial.h"
#include "/usr/local/polysync/include/polysync_shdmem.h"
#include "/usr/local/polysync/include/polysync_socket.h"
#include "/usr/local/polysync/include/polysync_transform.h"
#include "/usr/local/polysync/include/polysync_video.h"
#include "/usr/local/polysync/include/preco_gen3_driver.h"
#include "/usr/local/polysync/include/quanergy_m8_driver.h"
#include "/usr/local/polysync/include/sainsmart_usb_driver.h"
#include "/usr/local/polysync/include/swiftnav_piksi_multi_driver.h"
#include "/usr/local/polysync/include/sync_trigger_usb_driver.h"
#include "/usr/local/polysync/include/velodyne_hdl32e_driver.h"
#include "/usr/local/polysync/include/velodyne_vlp16_driver.h"
